### ISSUE TITLE
"amber new project" should not create a project in an existing, non-empty folder

### ISSUE THREAD

**Issue by piedoom** [amberframework/amber#1076]
### Description

Currently, `amber new folder_name` will create a new project within `folder_name`, even if that folder already exists.

### Steps to Reproduce

1. Create any folder, fill it with content if you like.  Or run `amber new xxx` twice

**Expected behavior:** The program should read that a non-empty folder already exists, or prompt the user to create the project within a unique folder. This is how most CLI frameworks I've worked with function - for instance, Rails.

**Actual behavior:** All contents are merged

**Reproduces how often:** 100%

### Versions

```
Crystal 0.27.2 (2019-02-05)

LLVM: 6.0.1
Default target: x86_64-apple-macosx

Amber CLI (amberframework.org) - v0.11.3
```

**Comment by kvirani** [comment]
Reproduced with 

```
Amber CLI (amberframework.org) - v0.27.0
```

That said, the behaviour is non-destructive. Amber doesn't replace _any_ existing files with their original/templated versions if they already exist. 

So the worst that will happen is that you will end up with a "not so new" Amber app in a target directory (which already existed and had some of the files in there already) but it won't work because it's not technically a _clean & new_ app folder. 

So since it's not destructive I wonder if we can just like this behaviour as is?

**Comment by elorest** [comment]
@kvirani That would be my preference.

**Comment by piedoom** [comment]
I'll leave that decision to you, close if needed.

**Comment by nsuchy** [comment]
@elorest In theory we could output a warning but at that point the "damage" (in this case unwanted files) are already added. The alternative would be requiring a `--skip-existing-files-check` flag to create in a folder with other files.

However it might be desirable (although maybe messy) to create in an existing project folder, for example hypothetically I have a rails app I want to migrate over to amber so I create the amber files in the rails folder and port stuff over model by model, controller by controller, eventually removing all rails related files.

In this case I'm not sure Amber can address without creating problems for people who need to create projects in an existing folder.

**Comment by drujensen** [comment]
#1018 will fix this by enabling interactive mode by default.  You can disable it using a `-y` flag.
