### ISSUE TITLE
routes resources  without / prefix

### ISSUE THREAD

**Issue by pynixwang** [amberframework/amber#1082]
### Description

```crystal
routes :api, "/api" do
    resources "/pets", PetController
  end
```
this works well , but not work without "/" prefix. 

add "/" prefix to scope is not bad.
but to resources is not acceptable.

**Comment by kvirani** [comment]
Would love a PR from you on this @pynixwang. 

I see in your commits that you've made the change but 

a) it should support both _without_ `/` and _with_ it so that it's backward compabile: if `/` is added then it _should not_ do `//`
b) we should add specs to test both without and without `/` that support this.

If you don't have the time for the changes above and the PR, then I can take it on, using your code as the starting point.

Let me know how you'd like to proceed.

**Comment by pynixwang** [comment]
I 'm a little busy these days, and the framework is not api stable, we can do breaking change now, and this is really a "dsl", prefix on scope is  optional, but resources with it is bad idea.

**Comment by elorest** [comment]
@pynixwang the framework is/should be api stable. Many people are using it in production so in general we want to avoid breaking changes.
