### ISSUE TITLE
incorrect crystal version and symlinks

### ISSUE THREAD

**Issue by bbaragar** [amberframework/amber#1127]
Crystal version incorrect in 2 files, should be 0.30.1:
    .crystal-version
    shard.yml

The symlinks in the makefile seem to be created correctly

**Comment by drujensen** [comment]
Is this causing any issues for you?  We typically don't update the crystal version for every patch release.

**Comment by bbaragar** [comment]
Yes when I try to build amber it throws errors about version 0.28.0 or 0.29.0 not being installed. changing the version in the two files to 0.30.1 fixed this

**Comment by elorest** [comment]
Hmmm. We recently released amber to work with multiple breaking changes in 0.30.x. Thanks for that @drujensen. Anyway shards.yml is locked to crystal version 0.29.0 and .crystal-version is locked to 0.28.1. Since the currently naming convention mirrors the crystal version I would assume it's preferred version would also be 0.30.x even if it was possible to compile with an older version.

Do you have any issues with me changing that and releasing 0.30.1?

**Comment by drujensen** [comment]
fixed by #1128
