### ISSUE TITLE
Sanitizing values rendered in views

### ISSUE THREAD

**Issue by Uzay-G** [amberframework/amber#1198]
I am using ECR to render my views, so for example in one of my views I have:
```<%= user.name %>```

The problem with this is that I noticed if for example my user's name is `<h1>User</h1>`, the html actually gets rendered ( and with it all the js vulnerabilities you can think of. ). The way Rails handles this is that any erb variable gets sanitized for html. Maybe, since amber supports several templating languages, we could create a function `sanitizeHTML()` that could strip all this dangerous code that would be used in the views.

**Comment by drujensen** [comment]
@Uzay-G Thanks for reporting this.  The ECR is apart of the crystal library and not something we recommend using.  slang and other templating languages handles the sanitization for you.

We have considered removing support for ECR because of this concern but it is a popular format for people that prefer html templates over a transpiler.

Maybe someone would be interested in submitting a fix for this in the crystal library or creating an alternative? 🙏

**Comment by Uzay-G** [comment]
Alright thanks @drujensen. How can I migrate my webapp to slang if i am using ecr?

**Comment by drujensen** [comment]
@Uzay-G If it was me, I would first change the `language: ecr` to `language: slang` in the `.amber.yml`.  Then I would run `amber g scaffold sample name:string body:text flag:bool` to provide sample code to look at.  Then I would look at the slim templating language at http://slim-lang.com since Slang is pretty similar to it.  There is a little bit of a learning curve but once you get used to it, it will be hard to go back to ECR or ERB.

**Comment by Uzay-G** [comment]
Im having problems transferring. I changed the config but I am getting this error:
```
There was a problem expanding macro 'embed'

Code in macro 'embed'

 4 | ECR.embed("src/views/user/dashboard.ecr", "__kilt_io__", )
     ^
Called macro defined in /usr/share/crystal/src/ecr/macros.cr:69:3

 69 | macro embed(filename, io_name)

Which expanded to:

 > 1 | {{ run("ecr/process", "src/views/user/dashboard.ecr", "__kilt_io__") }}
          ^--
Error: Error executing run (exit code: 1): ecr/process "src/views/user/dashboard.ecr" "__kilt_io__"
```
