### ISSUE TITLE
API returns 403

### ISSUE THREAD

**Issue by Uzay-G** [amberframework/amber#1199]
I am building a scaffold for a simple JSON API. This is my controller:

```ruby
class StatsApiController < ApplicationController
    def json_api
       bot = Bot.find_by(token: request.headers["key"])
       halt!(401, "Unauthorized") if bot.nil?
       return 200
    end
end
```
And in my routes:
```ruby
  routes :api do
    get "/send_data", StatsApiController, :json_api
  end
```

Now I tried running a request with curl and my browser on my endpoint like this:
```
curl -H "key: <key>" http://localhost:3000/send_data
```
Unfortunately, I am getting a 403 Forbidden response. This is surprising considering the endpoint should either return 401 or 200. Is there some sort of config I need to set to allow api requests?
It works when I put the view in the `web` pipeline.

**Comment by drujensen** [comment]
@Uzay-G The API generator includes the CORS pipeline which requires a -H "origin: " header.  You can set the origin to anything since it defaults to `*` but it is a required header according to the spec.

You can find the relevant code here:  https://github.com/amberframework/amber/blob/master/src/amber/pipes/cors.cr#L29

**Comment by Uzay-G** [comment]
Ok thanks
