### ISSUE TITLE
Missing css version amber 1.3.0

### ISSUE THREAD

**Issue by lebogan** [amberframework/amber#1299]
Help please. I am trying to use Amber on Ubuntu 20.04. Following the docs, I have Crystal 1.6.1, nodejs 12, and webpack installed. Running amber watch gives a cryptic error about missing package.json.23......

**Comment by crimson-knight** [comment]
@lebogan can you please share the whole error? It sounds like you didn't install the node dependencies.

And I highly recommend node 16+ if you're using Amber 1.3+.

Where in the docs did it say to use Node 12? I need to update that :)

**Comment by lebogan** [comment]
@crimson-knight, in my .npm/_logs...debug.log not the docs:
```
10068 warn notsup Not compatible with your version of node/npm: sass-loader@13.1.0
10069 verbose notsup Not compatible with your version of node/npm: sass-loader@13.1.0
10069 verbose notsup Required: {"node":">= 14.15.0"}
10069 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
10070 warn notsup Unsupported engine for node-sass@7.0.3: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
```
I  installed nodejs from the apt repo, obviously not the latest. I am reinstalling node v18.12.0 and trying again.

....

Ok. We are styling. One error popped up during `amber new ...`  about :
```
Shard "inflector" version (0.1.8) doesn't match tag version (1.0.0)
```
Is this any cause for concern down the road.

Thank s for the quick response. I really appreciate that! Is there a minimum version requirement list in the docs?

**Comment by crimson-knight** [comment]
Yeah that error happens, but it won't effect anything in the future. It's just because there's a constant in that shard that wasn't updated to match the version.

We don't have a minimum version requirement listed anywhere currently, I think as of Amber 1.0 we only support Crystal 1.0+ though (and most people don't use a Crystal version manager to remain on out dated versions of Crystal). As far as node goes, 14 is the lowest version I expect to work because anything lower than that is end-of-life. Here's a handy chat to show where it's at in the life cycle: https://endoflife.date/nodejs

In your error message at the end it says it only detected node v10, so I'm sure that was a big contributing factor to Webpack not working properly.

I rarely ever come across anyone using the apt version of node, most people use nvm and install some form of latest LTS version like 16 or 18.

I did test the latest release with Node 14 and it does work, but that's as far back as I'm willing to test. I'll add a page to the docs for some extra info about this. 

I'm going to close this issue out since you're issue was resolved. If you run into any other issues or have questions on how to do something, please feel free to open an issue here or join us on discord https://discord.gg/vwvP5zakSn
