### ISSUE TITLE
Support HEAD requests

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#233]
currently HEAD is returning 404
`curl --head http://localhost:3000`

**Comment by docelic** [comment]
The issue seems to be that HEAD is treated as a standalone action and unless an explicit 'head' for a resource exists in routes, 404 is returned.

RFC2616 says for HEAD:
"The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request.:

Based on that, I believe the code would need to work like this:

1) If HEAD route specifically exists, use that route. When data is returned to client, do not send any body, even if route generated some
2) If a specific route does not exist, and if HEADs are enabled by default (config option, default: true), then follow the route identical as GET, but in the end return everything except actual response body
3) If a specific route does not exist, and HEADs are disabled in configuration, keep current behavior

Sounds good?

**Comment by drujensen** [comment]
@docelic that is correct.  The way that Kemal and Kemalyst do this is add a HEAD route for every GET route.  We will need to avoid sending the body back if the request is a HEAD request.

https://github.com/kemalyst/kemalyst/blob/master/src/kemalyst/handler/router.cr#L144

**Comment by docelic** [comment]
Ok submitted a basic PR in https://github.com/amberframework/amber/pull/497.

This needs some little bit of work before merging:

-----------
1) Currently, since HEAD is always added for GETs, it is impossible to create a custom, specific HEAD route if GET action exists as well, because the one added by GET will cause Amber::Exceptions::DuplicateRouteError)

This needs to be solved in any way we want:

1) We delete old route, create new one
2) Or we do not add automatic HEAD on GET if custom HEAD already exists
3) But if we choose #2, what if user first defines a GET, and then his custom HEAD (he'll get above error).
Is #3 that OK? Do we want to force users to pay attention to order of routes? Or we add another field to routes which specifies whether route was automatically or manually created, and if automatically, then those routes are removed in favor of custom/manually-defined ones.

-----------
2) Do we want a config option to control if HEADs are automatically created?

-----------
3) Specs are needed

**Comment by eliasjpr** [comment]
Fixed with https://github.com/amberframework/amber/pull/506

Thanks to @docelic 🙌
