### ISSUE TITLE
including css / assets

### ISSUE THREAD

**Issue by sam0x17** [amberframework/amber#298]
Can we get some info about the asset pipeline and just like some really basic basics? For example, in the default project there is `assets/stylesheets/main.scss` but from what I can tell this file does not get complied to css or included in the default homepage (in the head section of the resulting HTML, I only see a stylesheet tag for bootstrap). What am I missing? How do I include app-generated CSS/SASS assets in a layout?

Thanks!

**Comment by drujensen** [comment]
Thanks for the request.  I will spend some time documenting it.

To answer your question regarding stylesheets, they are being included in the `public/dist/[name].bundle.js`.  You can see the web pack configuration in `config/webpack/common.js`.  There is a style, css, sass, and file loader defined that handles merging them into the bundle.  The file loader handles including images and fonts.

In order to compile, you will need to install either npm or yarn.  Then you will need to install the npm packages using `npm install`

Next, there are three scripts defined for you in the `package.json`.  You can execute the scripts using `npm run compile`, npm run watch` or npm run release`.

**Comment by sam0x17** [comment]
ok thanks!

**Comment by Rhainur** [comment]
I think this needs to be given much higher priority in the documentation! Coming to Amber from Rails, when I saw that NodeJS was listed as an optional requirement for installation, I assumed that assets would be compiled automatically and spent quite a long time trying to understand why my changes weren't being reflected in public/dist/main.bundle.js

Then I tried deleting that file and spent even longer trying to figure out why it wasn't being recreated. :(

At the very least, a warning that asset compilation is not automatic would be really helpful. I was relying on "amber watch" because I had no reason to think otherwise

**Comment by sam0x17** [comment]
I agree @Rhainur, though I also am a bit uncomfortable with the idea of loading all styles via js. It seems to be slower than pure css as there is like an 80ms period I can visually see where the page has no style before the js is loaded. All this new-fangled webpack stuff is cool, but tbh my expectation was that amber would simply have a fast asset compilation pipeline that produces minified CSS from sass/etc instead of relying on node to do this. Surely there is a C++ library that does this that we could simply use natively in amber?

**Comment by drujensen** [comment]
@sam0x17 @Rhainur thanks for the feedback.  We have discussed looking into a native solution for asset compilation.  @elorest has been advocating this as well.

The argument for using npm/webpack is that more projects are heading that direction and it gives you a good starting point for integrating a JS framework.  It didn't seem logical to have both a native solution and npm/webpack solution and the feeling is that more projects will want the npm/webpack solution.

One thing we want to do is change `amber watch` to allow you to configure watching and running multiple processes.  This would allow us to add `npm watch` to `amber watch` so you don't need to launch both.

Thoughts?

**Comment by Rhainur** [comment]
I might be out of touch with cutting edge development, but is it really the trend to merge all your CSS with your JS? I think separate CSS/JS output will be faaaaar more desirable, but I have no statistics to back me up :(

Anyway, what I ended up doing was ignoring the default pipeline, and using Gulp and Rollup instead.

(Unfortunately about an hour after that I ran into other issues which made me give up on Amber for the time being and go back to Rails, but that's a whole other problem, and if I can find the time I'll try to learn enough Crystal to contribute to this project)

**Comment by aarongodin** [comment]
Separate JS and CSS files as your dist is certainly preferred in most cases. I'm not sure if this has changed recently, but that's already the case with amber's generated webpack config (config/webpack/common.js) At the end of the day, I would see this being up to the individual developer. Given that Amber is only suggesting that your pipeline for building JS and CSS is that it's done through webpack, you're afforded a lot of flexibility.

I'm curious what ambitions Amber has in terms of automating any pieces of frontend build. Frameworks like Rails always were a little over-ambitionous in my opinion.

**Comment by Rhainur** [comment]
> Separate JS and CSS files as your dist is certainly preferred in most cases. I'm not sure if this has changed recently, but that's already the case with amber's generated webpack config (config/webpack/common.js)

My project was generated with 0.2.7 and common.js uses style-loader to merge the CSS into the JS. The input file (main.js) has a line that imports CSS and there is only one output file, although the views do load the bootstrap CSS directly from the CDN

**Comment by aarongodin** [comment]
Gotcha. Looks like this has changed, as a new app in 0.3.0 is using extract-text-webpack-plugin (in addition to style-loader like you described) to create a separate bundle for the CSS. Also to note here is that I've only run the generator with `-t ecr` and not slang which is the default.

**Comment by drujensen** [comment]
Yes, this was changed and the `css` and `js` are separate bundles in 0.3.0.

**Comment by imdrasil** [comment]
@drujensen I'm going to work on smth similar to [webpacker](https://github.com/rails/webpacker). So if you have some suggestions or ideas - will be glad to hear them ).

**Comment by eliasjpr** [comment]
Closing based on @drujensen answer 
> Yes, this was changed and the css and js are separate bundles in 0.3.0.

**Comment by CaDs** [comment]
Hello

Currently I'm struggling with this. 
Was the assets-related information, added to the documentation somewhere?

Thanks

**Comment by robacarp** [comment]
@CaDs if you're still struggling with this, please open a new issue.
