### ISSUE TITLE
Caching Shards?

### ISSUE THREAD

**Issue by Kentoseth** [amberframework/amber#341]
### Description

Is it possible to cache the shards and then share those saved packages across different projects (when creating a new project)?

Currently when I attempt to create 2 or 3 different projects, it is re-downloading the same shards each time, whereas I already have them all downloaded locally.

If this doesn't exist already, it can be considered a `feature`

### Steps to Reproduce

1. `amber new blog1`
2. Now in an alternative directory: `amber new blog2`
3. I tried to copy/paste both `lib/` and `.shards/` each to a new project, but when running `shards install` it still re-downloads the shards.
4. I also tried to create a project within an existing-project (assuming `shards` would be fetched upstream), but it still downloads the `shards`

**Expected behavior:** [What you expect to happen]

It should be possible to cache and share packages across projects (or cache the projects at a higher level and let different projects fetch from the cache first)

**Actual behavior:** [What actually happens]

Shards are downloaded repeatedly.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

You can get this information from copy and pasting the output of `amber --version` and `amber --version` from the command line. Also, please include the OS and what version of the OS you're running.

Amber CMD (amberframework.org) - v0.3.0

**Comment by Kentoseth** [comment]
## Suggestion

Before downloading, the `shards install` should check for existing packages.

Based on the fact that the issue is with `shards`, I am assuming this may be an upstream issue.

**Comment by marksiemers** [comment]
@Kentoseth - I do believe what you are asking is an issue with shards rather than amber.

There is an open issue https://github.com/crystal-lang/shards/issues/180 - this doesn't have to do with caching, but it will make downloading shards much faster (for `amber` and `amber-spec` specifically).

Basically, the `amber` and `amber-spec`, the repo sizes are very large, but any given release is very small. Right now `shards` will clone the whole repo instead of grabbing a release.

If the aforementioned issue is resolved, I think you will care about caching less, but it is still a good feature for shards to have.

**Comment by Kentoseth** [comment]
Please refer to issue in the other thread.
