### ISSUE TITLE
Unexpected restarting server loop

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#469]
### Description

Recently we implemented a restart loop to restart amber server when it fails (see #443). However this behavior is unexpected in other conditions like `bind: Cannot assign requested address` and other deploy errors. So instead of failing once, the server never starts but keep in a restart loop taking CPU at 100%.

### Steps to Reproduce

1. Configure development.yml with a wrong IP
2. Try to start the compiled server `./bin/myapp`
3. See restart loop and 100% of CPU usage.

**Expected behavior:** `./bin/myapp` fails once, showing error

**Actual behavior:** `./bin/myapp` fails forever, showing a restart loop and taking 100% CPU

**Reproduces how often:** 100%

### Versions

Amber `v0.5.0`

### Additional Information

![screenshot_20171231_153419](https://user-images.githubusercontent.com/3067335/34464098-128108a6-ee40-11e7-9169-6f3a2f53f87c.png)

I had to do `pkill myapp` because I was unable to use `Ctrl+C`. The restarting loop was too heavy 😞

**Comment by eliasjpr** [comment]
This is something that was added recently here https://github.com/amberframework/amber/blob/master/src/amber/server/server.cr#L70 I am not a fan of the approach but this was to address a specific issue. See https://github.com/amberframework/amber/pull/443

**Comment by faustinoaq** [comment]
@eliasjpr Yeah, I understand, but I think we should avoid restarting for first start. I mean:

```crystal
break if !@app_running
```

Like I implemented here 👉 https://github.com/amberframework/amber/pull/457/files#diff-9b4b623c272084b77e1c74c4e3111a48R36

BTW, on latest amber `v0.6.0`, `npm install && npm run watch` is executed on every change, is a bit annoying 😅 , also fixed here 👉 https://github.com/amberframework/amber/pull/457/files#diff-9b4b623c272084b77e1c74c4e3111a48R71 (run npm once at beginning)

**Comment by veelenga** [comment]
Why not to stop restarting it after a couple of failed attempts:

```crystal
attempts = 0

loop do
  begin
    attempts += 1
    puts "trying to start server"
    raise Exception.new
  rescue e : Exception
    raise e if attempts >= 3
    puts "restarting"
  end
end

# trying to start server
# restarting
# trying to start server
# restarting
# trying to start server
# (Exception)

```

**Comment by elorest** [comment]
I have a solution to this issue. Turned out that getting 0.24.1 working
took a lot more time so I didn't merge it in.

**Comment by elorest** [comment]
@veelenga The reason I didn't choose that solution is that I don't want a DDOS to be able to crash the server permanently. If I just restart it 3 times then I might as well not even restart it at all since it someone would just have to hit it a few seconds longer to take it down for good.

The Exception I'm rescuing from covers too many things so I'm going to need to just check the message as well before determining if I should restart or exit.

```cr
if ex.message ==  "accept: Too many open files" 
  puts "restarting..."
else
  puts ex.message
  exit
end
```

**Comment by veelenga** [comment]
@elorest sorry, i didn't follow the issue it is intended to solve, that's why i didn't understand what that `loop` was for. But now I do and DDOS example is a good argument 👍 

I didn't notice that issue since heroku automatically starts the app after the failure and even periodically restarts it once per day.

**Comment by elorest** [comment]
Yeah exactly. Rails handles this with a rescue retry. Crystal doesn't have that so I used a loop as suggested by @asterite. On Digital Ocean I also wrote a script to restart it if it fails but it's nice not to have to worry about that.
