### ISSUE TITLE
[RFC] Delegate many methods on Controller to Context or not?

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#565]
Currently, in Amber::Controller::Base, there is this:

```crystal
    delegate :client_ip,
      :cookies,
      :delete?,
      :flash,
      :format,
      :get?,
      :halt!,
      :head?,
      :patch?,
      :port,
      :post?,
      :put?,
      :request,
      :requested_url,
      :request_handler,
      :response,
      :route,
      :session,
      :valve,
      :websocket?,
    to: context
```

Due to delegation, all these methods from context become available directly on the controller.

However, since both the base controller and other controllers could reasonably be expected to be modified/extended by users, it would seem that this "duplication" of various methods with various names is undesired.

(It increases the chance of naming conflicts and makes things appear more automagical than they should be.)

Since "context" is always available within the controller, I would suggest not doing any delegations, and instead requiring people to properly call `context.<method>`.

Comments welcome.

**Comment by eliasjpr** [comment]
The reason we did add these delegation

1- Keep similar API to Rails to make transition easier.
2- to avoid having people work directly with the context.
3-  Stay closer to the law of Deméter

Consider formins

**Comment by robacarp** [comment]
I'd rather leave these as delegated methods. Because of the way delegate works [it doesn't prevent someone](https://carc.in/#/r/3fgz) from overriding them, which is a good thing. That allows room for shards which extend or override functionality to do so. 

Along the lines of what @eliasjpr said about decoupling (Law of Demeter), I think of this as a collection of things which an action needs to know about that happen to come from the context. From the controller-action developer, they don't care where or how the methods are define, just that they are available in the action.

**Comment by drujensen** [comment]
I agree that these delegate methods clutter up the namespace in the controllers.  The trade off is requiring `context.*` all over the place instead.

I vote to keep the delegates but I would like to consider removing some of the less frequently used ones.

Here is the list of ones I think we could consider removing:
```
:client_ip,
:port,
:requested_url,
:request_handler,
:route,
:valve,
```

**Comment by robacarp** [comment]
@drujensen the only one that stands out to me as something I've used with any regularity is `requested_url`. I assume that can still be gotten via request? 

I have at one time or another looked for the client_ip, but that's far less frequently

**Comment by docelic** [comment]
Yeah, but shouldn't we either remove all, or keep all? It would be pretty hard to explain the difference in user documentation, and also frequency of use as a criterion can vary, depending on what the person is actually doing.

How about making a policy to include everything on the controller then? If we did that, I also think we could replace the current manual list of delegated items with a method_missing macro that rewrites everything that's missing to 'context'? Or this would make debugging harder?

**Comment by robacarp** [comment]
The only thing I really feel passionate about is that we shouldn't use method missing to patch the methods in. Whatever seems relevant to a "reasonable application dev" in an action should be available with as little object-hopping as possible.

**Comment by eliasjpr** [comment]
I honestly don't see the need to remove the delegates for the mere justification of cluttering the controller, because stylistics. Delegating is valid approach/pattern in this circumstance. These are convenience methods that maybe are not use as frequent as one would want but many of those methods are in fact useful to have in a controller. 

If clutter and the delegation pattern is the concern then my propositions is the followiing

- Remove the methods from the context
- Remove the delegates from the Controller
- Create a module with these methods in ./src/controller/helpers.cr and include the module in the controller

Even if we do the above, is accomplishing the same for not real added benefit, except the fact that we have module to maintain. See for example https://github.com/rails/rails/blob/b9a5fd706a821401cbe3ce11d7a18daa8267588f/actionpack/lib/action_controller/base.rb#L203

**Comment by eliasjpr** [comment]
> (If we did that, maybe we could also replace the current manual list of delegated items with a method_missing macro that rewrites everything that's missing to 'context'? Or this would make debugging harder?)

there is a macro called `forward_missing_to` which conceptually accomplishes the same thing with the removed benefit that forward missing will have to wait until the compiler sees that there is not method defined to then call method missing and then handle the method call. Delegate on the other hand just call the method on the correct object

**Comment by drujensen** [comment]
Yeah, @eliasjpr has some valid points.  I say we leave it as is.  The delegate pattern is a valid pattern and the possibility of a naming collision is low. If you write a `port` method in your controller, you get what you deserve.  ;-)

**Comment by docelic** [comment]
Ok, sounds good.
