### ISSUE TITLE
[CLI] Allow piped content for 'amber exec'

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#585]
Currently, it seems it is not possible to read code from STDIN, so this doesn't work:

echo "script contents" | amber exec
amber exec < /from/file

Also, there seems to be a (rather unusual) behavior where the argument to exec is checked whether it exists as a file, and if not it is executed as an in-place code.

For example:

amber exec test  --> if file 'test' exists, executes it
amber exec test  --> if file 'test' does not exist, tries to execute code "test"

This is quite non-standard, and interpretation of filename as code should not be happening. It should be removed in favor of the mentioned support for reading from STDIN. (I.e. if exec is running interactively, editor is opened; if not running interactively, STDIN is read.)

**Comment by sam0x17** [comment]
Totally agree on the STDIN, but I think the filename check is extremely slick. Wish more utilities worked this way.

**Comment by sam0x17** [comment]
@docelic I'm assuming the reason this feature (the filename check) might be "undesirable" would be that it is technically possible for a file to exist in the current directory with the same name as some valid bit of crystal code, making it ambiguous/non-obvious whether the file would be executed or the line of crystal code would be executed. There are two mitigations I could see to reduce the chances of this happening, though I would argue the ease-of-use gains of not disabling this far outweigh the benefits:

1.  (100% mitigation / ambiguity is impossible): require filenames to always contain a `/` character, meaning for files in the current directory you have to do `./file`. This makes it impossible for there to be a case where valid crystal code is a also a filename that exists. Users of Node.js will be familiar with this requirement e.g. requiring files in the same directory etc.
2. Require `.cr` to be at the end of the downcased filename. While it is possible to have a class like `MyFile` with a class method `cr`, where `MyFile.cr` also exists in the current directory, this would be uncommon to the point where the example is essentially contrived.
3. Specify filenames OR code as a command-line arg. In this case I would advocate `amber exec [crystal code here]` having precedent, so we would have that syntax plus `amber exec -i filename.cr`. This is less exciting, but eliminates any ambiguity, for sure.

Regardless of what we do, the docs are pretty clear about what will happen even in the ambiguous cases (if the file exists, that will execute, otherwise attempt to execute as crystal code).

Thoughts?

**Comment by robacarp** [comment]
Yeah, the command is trying to be clever and I think it actually has some potential to cause unintended consequences as a result. Looking for a `.cr` isn't really that different. If something needs to be done, a `-f` flag seems appropriate for reading from a file.

I don't really know where the line between shell and binary lies...it always surprise me how much logic lives on both sides of that divide. I have this hunch that if it's done properly, a bunch of this logic would be free because it's already handled by the shell.

I'm thinking off the cuff of what I might expect a command like this to do in different circumstances:

1) `amber exec -f create_user.cr # reads file and evals it`
2) `amber exec # waits for user input on STDIN, ctrl-d to signal EOI and then execute it all at once`
3) `amber exec 'User.create(name: "rob")' # execute straight from command args`
4) `amber exec -c 'User.create(name: "rob")' # execute from parameter`
5) `amber exec < create_user.cr # read STDIN and execute`

They could probably all coexist.

I think @elorest might have some opinions about this. I think the `amber exec` command came in pretty quickly when the damage that could be accidentally wrought by the now removed `amber cli` command was found out.

**Comment by faustinoaq** [comment]
> `amber exec # waits for user input on STDIN, ctrl-d to signal EOI and then execute it all at once`

I like this one 👍

**Comment by elorest** [comment]
`amber exec` opens editor and executes on save/exit already.

I'm fine with everything except for 2, and I don't fully understand 5.

**Comment by elorest** [comment]
@sam0x17 @robacarp I don't really care if it checks if its a file or uses a `-f` flag. 

However, it seems extremely unlikely that a valid command could be a file. 

In the case that it does it won't matter anyway because it opens it in a buffer so you can verify it. It the case it's not right don't run it.

**Comment by sam0x17** [comment]
@elorest as you know, I agree with regards to the unlikeliness

I do think we should at least have a _way_ to have it read STDIN, though not sure how we would want that to work. I'm assuming the motivation is piping.

I'm all for switching to `amber exec -f file.cr` if there is consensus (or adding it as an explicit option) but like you I prefer the old syntax.

do you have a snippet you use to add `amber exec` capability to arbitrary projects? or are you using amber as a dependency? I would love to use this everywhere XD

**Comment by robacarp** [comment]
Number 2 is a pretty common pattern. Ruby, Perl, python and others implement this functionality.

**Comment by robacarp** [comment]
I'd prefer spawning $EDITOR instead of the current functionality of requiring a user to pass in an editor command, or the number 2 functionality.

I didn't realize that when the argument is a file, `amber x` spawns an editor targeted at that file. I thought it just executed it. This is perhaps a nonstandard behavior and is _mostly_ harmless. But what happens when I accidentally target `amber x` at a file that:

- I most definitely cannot execute, **and**
- I most definitely cannot lose the contents of the file?

Is the only way to get out of the editor to execute the file? Seems dangerous. I suppose I could comment out the entire file and let it execute. Just now I was able to `^z` and `kill %1` without executing the file.

Here's a scenario:

```
$ echo puts Model.big_fat_database_destroying_query > puts
# later, perhaps days or months later, while doing something completely unrelated
$ amber x puts
```

It's easy to say "just don't do stupid stuff." I've watched as people name their tempfiles all sorts of nonsense and it wouldn't surprise me at all to see someone do exactly this. Substitute whatever code you want into the `puts` file. Maybe it becomes a place where a dev just stores a bunch of notes, who knows. [People do weird and unexpected things with software every day.](https://xkcd.com/763/)

My point is, it's risky behavior but it _doesn't have to be_. It's not hard to make it safe. But I digress.

---

On topic. There should be:

- a way to read from STDIN and execute it
- a flag to execute a file without spawning an editor

Regardless of my thoughts on spawning an editor above, I don't think it would be unreasonable to add this to the current command:

` -f filename.cr   # require config/application.cr and execute the file (no editor)`
` -f -                   # read from stdin, require config/application.cr and execute`

Additionally, I'd like to see an option which overrides the file which is required:

` -r <path/to/application.cr>    # require this file before executing, defaults to 'config/application.cr'`

**Comment by elorest** [comment]
> 
I didn't realize that when the argument is a file, amber x spawns an editor targeted at that file. I thought it just executed it. This is perhaps a nonstandard behavior and is mostly harmless. But what happens when I accidentally target amber x at a file that:
   * I most definitely cannot execute, and
   * I most definitely cannot lose the contents of the file?

It currently copies the file into temp with a timestamped filename like every other execution. This way it's not actually editing the file just the contents of the file. 

I understand that there are some use cases where you want to execute a file without reading it first and agree there should probably be an option for it. However, that isn't the primary use case for amber exec as one could just as easily run `crystal file.cr` if file execution is all that's needed.

**Comment by sam0x17** [comment]
@robacarp yes I originally intended for this to use the $EDITOR var, but I wasn't sure how and forgot about it

**Comment by docelic** [comment]
@sam0x17 in 'cry', we recently did:

class Options
  string ["-e", "--editor"], desc: "Prefered editor: [vim, nano, pico, etc], only used when no code or .cr file is specified", default: ENV["EDITOR"]? || "vim"
end
