### ISSUE TITLE
[Bash Script] Add ./bin/setup script to new Amber apps

### ISSUE THREAD

**Issue by ianagne** [amberframework/amber#597]
Hi all,

I recently started a small project with Amber , and I was awestruck by how easy it was to get to the feature development stage (even auth is covered ❤️ !).  The only thing I really had to add was a `./bin/setup` script, which I always add to new projects to install dependencies, set up the database, and alert users to project dependencies.  This makes it incredibly easy to onboard new developers.

Lucky framework has an example of what this looks like in practice:
https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/bin/setup

Is this something that you'd be interested to have auto-generated for new Amber apps?  I'd love to add it in if so.

**Comment by faustinoaq** [comment]
Hi @ianagne Thank you for open this issue!

We are discussing something like that here 👉 https://github.com/amberframework/amber/issues/582

**Comment by eliasjpr** [comment]
@ianagne to the app setup it only take a couple small steps 

- `shard build` this will build the amber cli under `bin/setup` (Only if you do not have the amber cli installed)
- `bin/amber db create migrate` to get the database create 

I believe that because of the simplicity of the steps the bin/setup.sh is not necessary
