### ISSUE TITLE
route_params should always be last param

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#772]
### Description

Suggested by @Sija on #745 via https://github.com/amberframework/amber/pull/745#issuecomment-384268502

> IMO the order of precedence is
> 
> ```
> query
> route_params
> multipart
> form
> ```
>
> The later overriding the previous.

`route_params` should always be last, otherwise taking `/user/:username` route as an example, sending `username` as multipart/form param would overwrite the former, which is a serious security consideration! :warning: 

### Steps to Reproduce

Not applicable, security request!

### Versions

Master https://github.com/amberframework/amber/commit/ae906b7d8a6cafc134555acf73b6e1f39fb4dbcf

### Additional Information

IMO This fix should be addressed before the next release :sweat_smile:

**Comment by robacarp** [comment]
Is this really is a security vulnerability?

If I have a route `POST /users/:id` and then someone posts to `/users/3` with something like `{id: 22, password: 'new password'}`, the parameter merge might overwrite the route param with the form data, but so what?

A malicious user could just as easily craft a form post directed at the url `/users/22` with `{password: 'new password'}`. Any manipulative override which can be done in a form body can just as easily be performed by manipulating the URL itself.

**Comment by Sija** [comment]
Well, as a developer I'd certainly **not expect** to have route params being overridden by params passed from another source. AFAIK Rails doesn't do this either.

**Comment by robacarp** [comment]
@Sija I agree, it's not what I'd expect. But I think it'll be easier to come to agreement around a concrete bug or workflow problem rather than a desire to be in parity with Rails. Without something concrete, this discussion doesn't seem like it'll be anything but opinions over semantics.

**Comment by elorest** [comment]
I believe after @eliasjpr rewrite of params it should return all of them unless you call to_h on it.

**Comment by eliasjpr** [comment]
@Sija Routes params do not get overriden in fact none of the params get overriden unless you call `to_h`. See https://github.com/amberframework/amber/blob/master/src/amber/router/params.cr#L32 

Be mindful that the route params are not technically params, since these params belong to the route. Rails provides methods such as `path_parameters` and `url_parameters`, we can easily expose each of the params, which was something I was considering at the time. Basically we can expose the following private methods:

```crystal
params.route # we can name this as path
params.query
params.form 
params.json 
params.multipart
```
The above is more explicit, and I personally like to have these methods accessible in parmas. Let me know what you guys think, is an easy change, we just have to remove the `private` keyword and add unit test.

The `[]` and `[]?` methods, attempts to find the params keys in any of those, so nothing is overwritten. The `to_h` method is something that has to be treated differently since this returns a flat hash of all the params., so some decisions sacrifices has to be made in the case when a duplicated key is found. 

I would have preferred not to have the `to_h` method available in params, since I do not see where would you need all the params in a single hash when they are clearly different scopes, and in the case of needing all params as a single hash that falls outside of the responsibility of `params` as an object.

**Comment by drujensen** [comment]
Closing this.  We will leave as is.
