### ISSUE TITLE
Add remote_ip to request

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#955]
### Description

Many people have asked how to find the ip of the client as they so easily can in Rails.
Rails does it with this middleware. Would be super useful to Amber and I'm sure Lucky, and Kemal if this middleware was converted to crystal.

https://github.com/rails/rails/blob/5-2-1/actionpack/lib/action_dispatch/middleware/remote_ip.rb

**Comment by firoxer** [comment]
I tried to do something about this but it turned out that Crystal is making things hard. As far as I understand Crystal provides no remote IP in the [Request](https://crystal-lang.org/api/0.26.1/HTTP/Request.html) object which would make it necessary to rely on headers such as `X-Forwarded-For`. Those, in turn, may not be reliable. There's some discussion about the matter in #534.

**Comment by nsuchy** [comment]
@firoxer It looks like one of the following needs to happen.

1) Someone contributes a change to the crystal standard library to add a remote IP to the Request object.

2) We create code which extends the standard library at runtime.

3) We write our own HTTP Server instead of relying on Crystal's built in one (which would add technical debt)

I found https://github.com/crystal-lang/crystal/issues/5784 and https://github.com/crystal-lang/crystal/pull/7610/files both being fairly recent and relevant to the issue at hand.

**Comment by eliasjpr** [comment]
This is fixed by standard library `HTTP::Request.remote_address` method see https://crystal-lang.org/api/0.34.0/HTTP/Request.html#remote_address:String?-instance-method
