### ISSUE TITLE
[Question] Creating custom generate commands

### ISSUE THREAD

**Issue by faissaloo** [amberframework/amber#970]
I would like to write something similar to https://github.com/galetahub/simple-captcha but I'm unsure of how I should write a shard that creates migrations, simple-captcha adds a `rails generate simple-captcha` command so I'm guessing it would be similar to that but I'm not sure how to go about adding that via a shard.

**Comment by robacarp** [comment]
@faissaloo Amber doesn't have hooks for dynamically modifying the `amber` binary command. Doing so in Crystal is more complicated than Ruby, because the binary needs to be recompiled or have an established hand off to a different binary (similar to git subcommands).

I've accomplished a decent workflow by writing a private shard which outputs a binary to my project `bin/`. Then, from an amber project, I run `bin/my_tool`. Shard.yml provides a postinstall hook which can [be used to compile and emit a binary](https://github.com/luckyframework/lucky/blob/master/shard.yml#L61-L74) when a helper shard is installed. If you go that route, bear in mind that this is a shared namespace, so try to make your binary uniquely named.

Hopefully that helps.

**Comment by faissaloo** [comment]
@robacarp Do you have a link to a shard you've done this in?

**Comment by robacarp** [comment]
@faissaloo no, sorry. The lucky project has several shards which do, and is linked in my previous comment.

**Comment by elorest** [comment]
Maybe not the best solution but you could easily overwrite templates before compiling amber_cli. I'm closing this for now, but feel free to continue the discussion.
